# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
