# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='references',
            field=models.ManyToManyField(db_table='references', related_name='referencers', to='notes.Note'),
        ),
    ]
