# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160826_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
