# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_document_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
