# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20161206_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
