# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexical_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalunit',
            name='category',
            field=models.SmallIntegerField(choices=[(0, ''), (10, 'N'), (20, 'V'), (30, 'ADJ'), (40, 'ADV')], default=0),
        ),
    ]
